### ISSUE TITLE
Thanks for your great and generous work!

### ISSUE THREAD

**Issue by wqking** [jzohrab/practicing-guitar#3]
Hello, I want to say thanks for your amazing work.
I found your book yesterday and I think it will help me a lot.
I don't play classical guitar, but I play Ukulele and Chromatic Harmonica, your book is useful for those instruments too. Indeed it's useful for any instruments IMHO.
I've shared your documents on a Ukulele forum to let others enjoy your work.

I have some suggestions on making your work more recognizable,
1, You may give more information on yourself, such as your real name, your youtube channel, your career, etc. I had a glance on your about page, but I still have no idea on who you are, then I can't remember you.
2, Compile the documents into a downloadable PDF to make it looks more like a real book. I think you may update the documents continuously but a download PDF is more convenient to read.
3, Give the book a unique and recognizable name, so the people can talk about your book on the forums and social medias.

**Comment by jzohrab** [comment]
Hi @wqking , thank you very much for this kind message!  It really brightened my day.

I am happy to have written it.  It's a bunch of ideas I'd found elsewhere, so it's not really "my" work :-)  Most of the ideas are from piano.  I agree it's mostly instrument-agnostic, and I thought about posting it in various forums to see if anyone wanted to adopt it to other instruments ... maybe I'll do that someday.

Great points re pushing the work out more, thank you.

Re point 1, I'm happy to sink into obscurity :-) , unless I publish some videos demonstrating these practice ideas.  But then, I'd want to be good enough that people really sit up and take notice, so that I become the example that I want to be, that this book talks about.  I get compliments on my playing and teaching, but like most people I have a bit of imposter syndrome, you know?

point 2 - the site is written with read the docs but I haven't tried to write the renderers for PDF.  I agree that would be useful for some -- but as I was writing it, I wasn't sure that PDF reading would be a necessity.  Who knows?  I think these ideas are worth publishing as an ebook or PDF or similar, just to keep getting them out there.

point 3 - yeah the name sucks doesn't it. :-)  There are so many good names out there already taken -- "the art of practicing", "the art of guitar", "scientific practicing" -- and I couldn't come up with a good one, without feeling presumptuous.

Thanks for sharing the book, again it was very gratifying to receive your note.  Cheers, Jeff
